// GENERATED smoke test: every forwarder of the functional numpy.polynomial modules agrees with PolyFunctional.
package numscala

class PolyModulesSuite extends munit.FunSuite:
  private val c = np.array(1.0, 2.0, 3.0)
  private val c2 = np.array(0.5, -1.0)
  private val x = np.array(-0.5, 0.25, 0.75)
  private val y = np.array(0.5, 0.0, -0.25)
  private val z = np.array(1.0, 2.0, 3.0)
  private val c3 = np.arange(8.0).reshape(2, 2, 2)
  private val c22 = np.arange(4.0).reshape(2, 2)
  private def same(a: NDArray[Double], b: NDArray[Double])(using munit.Location): Unit =
    assertEquals(a.shape, b.shape)
    a.toSeq.zip(b.toSeq).foreach((p, q) => assertEqualsDouble(p, q, 1e-12 * math.max(1.0, math.abs(q))))

  test("polynomial module forwarders") {
    val m = np.polynomial.polynomial
    assertEquals(m.polydomain.size, 2); assertEquals(m.polyzero.toList, List(0.0)); assertEquals(m.polyone.toList, List(1.0)); assertEquals(m.polyx.size, 2)
    same(m.polyval(x, c), PolyFunctional.valArr(PolyBasis.Power, x, c, true))
    same(m.polyval(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valArr(PolyBasis.Power, x(sliceTo(2)), c22, false))
    assertEqualsDouble(m.polyval(0.5, c), PolyBasis.Power.valScalar(0.5, Array(1.0, 2.0, 3.0)), 1e-14)
    same(m.polyval2d(x, y, c22), PolyFunctional.valNd(PolyBasis.Power, c22, x, y))
    same(m.polyval3d(x, y, z, c3), PolyFunctional.valNd(PolyBasis.Power, c3, x, y, z))
    same(m.polygrid2d(x, y, c22), PolyFunctional.gridNd(PolyBasis.Power, c22, x, y))
    same(m.polygrid3d(x, y, z, c3), PolyFunctional.gridNd(PolyBasis.Power, c3, x, y, z))
    same(m.polyvander(x, 3), PolyFunctional.vander(PolyBasis.Power, x, 3))
    same(m.polyvander2d(x, y, Seq(1, 2)), PolyFunctional.vanderNd(PolyBasis.Power, Seq(x, y), Seq(1, 2)))
    same(m.polyvander3d(x, y, z, Seq(1, 1, 2)), PolyFunctional.vanderNd(PolyBasis.Power, Seq(x, y, z), Seq(1, 1, 2)))
    same(m.polyder(c), PolyFunctional.der(PolyBasis.Power, c, 1, 1.0, 0))
    same(m.polyint(c, 2, Seq(1.0), 0.5, 2.0), PolyFunctional.integ(PolyBasis.Power, c, 2, Seq(1.0), 0.5, 2.0, 0))
    same(m.polyadd(c, c2), PolyFunctional.add(PolyBasis.Power, c, c2))
    same(m.polysub(c, c2), PolyFunctional.sub(PolyBasis.Power, c, c2))
    same(m.polymul(c, c2), PolyFunctional.mul(PolyBasis.Power, c, c2))
    same(m.polymulx(c), PolyFunctional.mulx(PolyBasis.Power, c))
    same(m.polydiv(c, c2)._1, PolyFunctional.div(PolyBasis.Power, c, c2)._1)
    same(m.polypow(c2, 2), PolyFunctional.pow(PolyBasis.Power, c2, 2, 16))
    assertEquals(m.polyroots(c).toList, PolyFunctional.roots(PolyBasis.Power, c).toList)
    same(m.polycompanion(c), PolyFunctional.companion(PolyBasis.Power, c))
    same(m.polyfromroots(c2), PolyFunctional.fromroots(PolyBasis.Power, c2))
    same(m.polyline(1.0, 2.0), PolyFunctional.line(PolyBasis.Power, 1.0, 2.0))
    same(m.polytrim(np.array(1.0, 0.0)), np.array(1.0).reshape(1))
    val xs = np.linspace(0.0, 1.0, 6)
    val ys = xs.map(v => v * v)
    same(m.polyfit(xs, ys, 2), PolyFunctional.fit(PolyBasis.Power, xs, ys, 2, -1.0, null)._1)
    assertEquals(m.polyfit(xs, ys, 2, full = true)._2.rank, 3)
    same(m.polyfit(xs, ys, 2, w = np.ones(6)), PolyFunctional.fit(PolyBasis.Power, xs, ys, 2, -1.0, np.ones(6))._1)
    same(m.polyvalfromroots(x, c22), PolyFunctional.valfromroots(x, c22, true))
    same(m.polyvalfromroots(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valfromroots(x(sliceTo(2)), c22, false))
    assertEquals(m.Polynomial(Seq(1.0)).degree, 0)
  }

  test("chebyshev module forwarders") {
    val m = np.polynomial.chebyshev
    assertEquals(m.chebdomain.size, 2); assertEquals(m.chebzero.toList, List(0.0)); assertEquals(m.chebone.toList, List(1.0)); assertEquals(m.chebx.size, 2)
    same(m.chebval(x, c), PolyFunctional.valArr(PolyBasis.Cheb, x, c, true))
    same(m.chebval(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valArr(PolyBasis.Cheb, x(sliceTo(2)), c22, false))
    assertEqualsDouble(m.chebval(0.5, c), PolyBasis.Cheb.valScalar(0.5, Array(1.0, 2.0, 3.0)), 1e-14)
    same(m.chebval2d(x, y, c22), PolyFunctional.valNd(PolyBasis.Cheb, c22, x, y))
    same(m.chebval3d(x, y, z, c3), PolyFunctional.valNd(PolyBasis.Cheb, c3, x, y, z))
    same(m.chebgrid2d(x, y, c22), PolyFunctional.gridNd(PolyBasis.Cheb, c22, x, y))
    same(m.chebgrid3d(x, y, z, c3), PolyFunctional.gridNd(PolyBasis.Cheb, c3, x, y, z))
    same(m.chebvander(x, 3), PolyFunctional.vander(PolyBasis.Cheb, x, 3))
    same(m.chebvander2d(x, y, Seq(1, 2)), PolyFunctional.vanderNd(PolyBasis.Cheb, Seq(x, y), Seq(1, 2)))
    same(m.chebvander3d(x, y, z, Seq(1, 1, 2)), PolyFunctional.vanderNd(PolyBasis.Cheb, Seq(x, y, z), Seq(1, 1, 2)))
    same(m.chebder(c), PolyFunctional.der(PolyBasis.Cheb, c, 1, 1.0, 0))
    same(m.chebint(c, 2, Seq(1.0), 0.5, 2.0), PolyFunctional.integ(PolyBasis.Cheb, c, 2, Seq(1.0), 0.5, 2.0, 0))
    same(m.chebadd(c, c2), PolyFunctional.add(PolyBasis.Cheb, c, c2))
    same(m.chebsub(c, c2), PolyFunctional.sub(PolyBasis.Cheb, c, c2))
    same(m.chebmul(c, c2), PolyFunctional.mul(PolyBasis.Cheb, c, c2))
    same(m.chebmulx(c), PolyFunctional.mulx(PolyBasis.Cheb, c))
    same(m.chebdiv(c, c2)._1, PolyFunctional.div(PolyBasis.Cheb, c, c2)._1)
    same(m.chebpow(c2, 2), PolyFunctional.pow(PolyBasis.Cheb, c2, 2, 16))
    assertEquals(m.chebroots(c).toList, PolyFunctional.roots(PolyBasis.Cheb, c).toList)
    same(m.chebcompanion(c), PolyFunctional.companion(PolyBasis.Cheb, c))
    same(m.chebfromroots(c2), PolyFunctional.fromroots(PolyBasis.Cheb, c2))
    same(m.chebline(1.0, 2.0), PolyFunctional.line(PolyBasis.Cheb, 1.0, 2.0))
    same(m.chebtrim(np.array(1.0, 0.0)), np.array(1.0).reshape(1))
    val xs = np.linspace(0.0, 1.0, 6)
    val ys = xs.map(v => v * v)
    same(m.chebfit(xs, ys, 2), PolyFunctional.fit(PolyBasis.Cheb, xs, ys, 2, -1.0, null)._1)
    assertEquals(m.chebfit(xs, ys, 2, full = true)._2.rank, 3)
    same(m.chebfit(xs, ys, 2, w = np.ones(6)), PolyFunctional.fit(PolyBasis.Cheb, xs, ys, 2, -1.0, np.ones(6))._1)
    same(m.cheb2poly(c), PolyFunctional.toPower(PolyBasis.Cheb, c))
    same(m.poly2cheb(c), PolyFunctional.fromPower(PolyBasis.Cheb, c))
    same(m.chebgauss(3)._1, PolyFunctional.gauss(PolyBasis.Cheb, 3)._1)
    same(m.chebweight(x), PolyFunctional.weight(PolyBasis.Cheb, x))
    assertEquals(m.Chebyshev(Seq(1.0)).degree, 0)
  }

  test("legendre module forwarders") {
    val m = np.polynomial.legendre
    assertEquals(m.legdomain.size, 2); assertEquals(m.legzero.toList, List(0.0)); assertEquals(m.legone.toList, List(1.0)); assertEquals(m.legx.size, 2)
    same(m.legval(x, c), PolyFunctional.valArr(PolyBasis.Leg, x, c, true))
    same(m.legval(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valArr(PolyBasis.Leg, x(sliceTo(2)), c22, false))
    assertEqualsDouble(m.legval(0.5, c), PolyBasis.Leg.valScalar(0.5, Array(1.0, 2.0, 3.0)), 1e-14)
    same(m.legval2d(x, y, c22), PolyFunctional.valNd(PolyBasis.Leg, c22, x, y))
    same(m.legval3d(x, y, z, c3), PolyFunctional.valNd(PolyBasis.Leg, c3, x, y, z))
    same(m.leggrid2d(x, y, c22), PolyFunctional.gridNd(PolyBasis.Leg, c22, x, y))
    same(m.leggrid3d(x, y, z, c3), PolyFunctional.gridNd(PolyBasis.Leg, c3, x, y, z))
    same(m.legvander(x, 3), PolyFunctional.vander(PolyBasis.Leg, x, 3))
    same(m.legvander2d(x, y, Seq(1, 2)), PolyFunctional.vanderNd(PolyBasis.Leg, Seq(x, y), Seq(1, 2)))
    same(m.legvander3d(x, y, z, Seq(1, 1, 2)), PolyFunctional.vanderNd(PolyBasis.Leg, Seq(x, y, z), Seq(1, 1, 2)))
    same(m.legder(c), PolyFunctional.der(PolyBasis.Leg, c, 1, 1.0, 0))
    same(m.legint(c, 2, Seq(1.0), 0.5, 2.0), PolyFunctional.integ(PolyBasis.Leg, c, 2, Seq(1.0), 0.5, 2.0, 0))
    same(m.legadd(c, c2), PolyFunctional.add(PolyBasis.Leg, c, c2))
    same(m.legsub(c, c2), PolyFunctional.sub(PolyBasis.Leg, c, c2))
    same(m.legmul(c, c2), PolyFunctional.mul(PolyBasis.Leg, c, c2))
    same(m.legmulx(c), PolyFunctional.mulx(PolyBasis.Leg, c))
    same(m.legdiv(c, c2)._1, PolyFunctional.div(PolyBasis.Leg, c, c2)._1)
    same(m.legpow(c2, 2), PolyFunctional.pow(PolyBasis.Leg, c2, 2, 16))
    assertEquals(m.legroots(c).toList, PolyFunctional.roots(PolyBasis.Leg, c).toList)
    same(m.legcompanion(c), PolyFunctional.companion(PolyBasis.Leg, c))
    same(m.legfromroots(c2), PolyFunctional.fromroots(PolyBasis.Leg, c2))
    same(m.legline(1.0, 2.0), PolyFunctional.line(PolyBasis.Leg, 1.0, 2.0))
    same(m.legtrim(np.array(1.0, 0.0)), np.array(1.0).reshape(1))
    val xs = np.linspace(0.0, 1.0, 6)
    val ys = xs.map(v => v * v)
    same(m.legfit(xs, ys, 2), PolyFunctional.fit(PolyBasis.Leg, xs, ys, 2, -1.0, null)._1)
    assertEquals(m.legfit(xs, ys, 2, full = true)._2.rank, 3)
    same(m.legfit(xs, ys, 2, w = np.ones(6)), PolyFunctional.fit(PolyBasis.Leg, xs, ys, 2, -1.0, np.ones(6))._1)
    same(m.leg2poly(c), PolyFunctional.toPower(PolyBasis.Leg, c))
    same(m.poly2leg(c), PolyFunctional.fromPower(PolyBasis.Leg, c))
    same(m.leggauss(3)._1, PolyFunctional.gauss(PolyBasis.Leg, 3)._1)
    same(m.legweight(x), PolyFunctional.weight(PolyBasis.Leg, x))
    assertEquals(m.Legendre(Seq(1.0)).degree, 0)
  }

  test("hermite module forwarders") {
    val m = np.polynomial.hermite
    assertEquals(m.hermdomain.size, 2); assertEquals(m.hermzero.toList, List(0.0)); assertEquals(m.hermone.toList, List(1.0)); assertEquals(m.hermx.size, 2)
    same(m.hermval(x, c), PolyFunctional.valArr(PolyBasis.Herm, x, c, true))
    same(m.hermval(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valArr(PolyBasis.Herm, x(sliceTo(2)), c22, false))
    assertEqualsDouble(m.hermval(0.5, c), PolyBasis.Herm.valScalar(0.5, Array(1.0, 2.0, 3.0)), 1e-14)
    same(m.hermval2d(x, y, c22), PolyFunctional.valNd(PolyBasis.Herm, c22, x, y))
    same(m.hermval3d(x, y, z, c3), PolyFunctional.valNd(PolyBasis.Herm, c3, x, y, z))
    same(m.hermgrid2d(x, y, c22), PolyFunctional.gridNd(PolyBasis.Herm, c22, x, y))
    same(m.hermgrid3d(x, y, z, c3), PolyFunctional.gridNd(PolyBasis.Herm, c3, x, y, z))
    same(m.hermvander(x, 3), PolyFunctional.vander(PolyBasis.Herm, x, 3))
    same(m.hermvander2d(x, y, Seq(1, 2)), PolyFunctional.vanderNd(PolyBasis.Herm, Seq(x, y), Seq(1, 2)))
    same(m.hermvander3d(x, y, z, Seq(1, 1, 2)), PolyFunctional.vanderNd(PolyBasis.Herm, Seq(x, y, z), Seq(1, 1, 2)))
    same(m.hermder(c), PolyFunctional.der(PolyBasis.Herm, c, 1, 1.0, 0))
    same(m.hermint(c, 2, Seq(1.0), 0.5, 2.0), PolyFunctional.integ(PolyBasis.Herm, c, 2, Seq(1.0), 0.5, 2.0, 0))
    same(m.hermadd(c, c2), PolyFunctional.add(PolyBasis.Herm, c, c2))
    same(m.hermsub(c, c2), PolyFunctional.sub(PolyBasis.Herm, c, c2))
    same(m.hermmul(c, c2), PolyFunctional.mul(PolyBasis.Herm, c, c2))
    same(m.hermmulx(c), PolyFunctional.mulx(PolyBasis.Herm, c))
    same(m.hermdiv(c, c2)._1, PolyFunctional.div(PolyBasis.Herm, c, c2)._1)
    same(m.hermpow(c2, 2), PolyFunctional.pow(PolyBasis.Herm, c2, 2, 16))
    assertEquals(m.hermroots(c).toList, PolyFunctional.roots(PolyBasis.Herm, c).toList)
    same(m.hermcompanion(c), PolyFunctional.companion(PolyBasis.Herm, c))
    same(m.hermfromroots(c2), PolyFunctional.fromroots(PolyBasis.Herm, c2))
    same(m.hermline(1.0, 2.0), PolyFunctional.line(PolyBasis.Herm, 1.0, 2.0))
    same(m.hermtrim(np.array(1.0, 0.0)), np.array(1.0).reshape(1))
    val xs = np.linspace(0.0, 1.0, 6)
    val ys = xs.map(v => v * v)
    same(m.hermfit(xs, ys, 2), PolyFunctional.fit(PolyBasis.Herm, xs, ys, 2, -1.0, null)._1)
    assertEquals(m.hermfit(xs, ys, 2, full = true)._2.rank, 3)
    same(m.hermfit(xs, ys, 2, w = np.ones(6)), PolyFunctional.fit(PolyBasis.Herm, xs, ys, 2, -1.0, np.ones(6))._1)
    same(m.herm2poly(c), PolyFunctional.toPower(PolyBasis.Herm, c))
    same(m.poly2herm(c), PolyFunctional.fromPower(PolyBasis.Herm, c))
    same(m.hermgauss(3)._1, PolyFunctional.gauss(PolyBasis.Herm, 3)._1)
    same(m.hermweight(x), PolyFunctional.weight(PolyBasis.Herm, x))
    assertEquals(m.Hermite(Seq(1.0)).degree, 0)
  }

  test("hermite_e module forwarders") {
    val m = np.polynomial.hermite_e
    assertEquals(m.hermedomain.size, 2); assertEquals(m.hermezero.toList, List(0.0)); assertEquals(m.hermeone.toList, List(1.0)); assertEquals(m.hermex.size, 2)
    same(m.hermeval(x, c), PolyFunctional.valArr(PolyBasis.HermE, x, c, true))
    same(m.hermeval(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valArr(PolyBasis.HermE, x(sliceTo(2)), c22, false))
    assertEqualsDouble(m.hermeval(0.5, c), PolyBasis.HermE.valScalar(0.5, Array(1.0, 2.0, 3.0)), 1e-14)
    same(m.hermeval2d(x, y, c22), PolyFunctional.valNd(PolyBasis.HermE, c22, x, y))
    same(m.hermeval3d(x, y, z, c3), PolyFunctional.valNd(PolyBasis.HermE, c3, x, y, z))
    same(m.hermegrid2d(x, y, c22), PolyFunctional.gridNd(PolyBasis.HermE, c22, x, y))
    same(m.hermegrid3d(x, y, z, c3), PolyFunctional.gridNd(PolyBasis.HermE, c3, x, y, z))
    same(m.hermevander(x, 3), PolyFunctional.vander(PolyBasis.HermE, x, 3))
    same(m.hermevander2d(x, y, Seq(1, 2)), PolyFunctional.vanderNd(PolyBasis.HermE, Seq(x, y), Seq(1, 2)))
    same(m.hermevander3d(x, y, z, Seq(1, 1, 2)), PolyFunctional.vanderNd(PolyBasis.HermE, Seq(x, y, z), Seq(1, 1, 2)))
    same(m.hermeder(c), PolyFunctional.der(PolyBasis.HermE, c, 1, 1.0, 0))
    same(m.hermeint(c, 2, Seq(1.0), 0.5, 2.0), PolyFunctional.integ(PolyBasis.HermE, c, 2, Seq(1.0), 0.5, 2.0, 0))
    same(m.hermeadd(c, c2), PolyFunctional.add(PolyBasis.HermE, c, c2))
    same(m.hermesub(c, c2), PolyFunctional.sub(PolyBasis.HermE, c, c2))
    same(m.hermemul(c, c2), PolyFunctional.mul(PolyBasis.HermE, c, c2))
    same(m.hermemulx(c), PolyFunctional.mulx(PolyBasis.HermE, c))
    same(m.hermediv(c, c2)._1, PolyFunctional.div(PolyBasis.HermE, c, c2)._1)
    same(m.hermepow(c2, 2), PolyFunctional.pow(PolyBasis.HermE, c2, 2, 16))
    assertEquals(m.hermeroots(c).toList, PolyFunctional.roots(PolyBasis.HermE, c).toList)
    same(m.hermecompanion(c), PolyFunctional.companion(PolyBasis.HermE, c))
    same(m.hermefromroots(c2), PolyFunctional.fromroots(PolyBasis.HermE, c2))
    same(m.hermeline(1.0, 2.0), PolyFunctional.line(PolyBasis.HermE, 1.0, 2.0))
    same(m.hermetrim(np.array(1.0, 0.0)), np.array(1.0).reshape(1))
    val xs = np.linspace(0.0, 1.0, 6)
    val ys = xs.map(v => v * v)
    same(m.hermefit(xs, ys, 2), PolyFunctional.fit(PolyBasis.HermE, xs, ys, 2, -1.0, null)._1)
    assertEquals(m.hermefit(xs, ys, 2, full = true)._2.rank, 3)
    same(m.hermefit(xs, ys, 2, w = np.ones(6)), PolyFunctional.fit(PolyBasis.HermE, xs, ys, 2, -1.0, np.ones(6))._1)
    same(m.herme2poly(c), PolyFunctional.toPower(PolyBasis.HermE, c))
    same(m.poly2herme(c), PolyFunctional.fromPower(PolyBasis.HermE, c))
    same(m.hermegauss(3)._1, PolyFunctional.gauss(PolyBasis.HermE, 3)._1)
    same(m.hermeweight(x), PolyFunctional.weight(PolyBasis.HermE, x))
    assertEquals(m.HermiteE(Seq(1.0)).degree, 0)
  }

  test("laguerre module forwarders") {
    val m = np.polynomial.laguerre
    assertEquals(m.lagdomain.size, 2); assertEquals(m.lagzero.toList, List(0.0)); assertEquals(m.lagone.toList, List(1.0)); assertEquals(m.lagx.size, 2)
    same(m.lagval(x, c), PolyFunctional.valArr(PolyBasis.Lag, x, c, true))
    same(m.lagval(x(sliceTo(2)), c22, tensor = false), PolyFunctional.valArr(PolyBasis.Lag, x(sliceTo(2)), c22, false))
    assertEqualsDouble(m.lagval(0.5, c), PolyBasis.Lag.valScalar(0.5, Array(1.0, 2.0, 3.0)), 1e-14)
    same(m.lagval2d(x, y, c22), PolyFunctional.valNd(PolyBasis.Lag, c22, x, y))
    same(m.lagval3d(x, y, z, c3), PolyFunctional.valNd(PolyBasis.Lag, c3, x, y, z))
    same(m.laggrid2d(x, y, c22), PolyFunctional.gridNd(PolyBasis.Lag, c22, x, y))
    same(m.laggrid3d(x, y, z, c3), PolyFunctional.gridNd(PolyBasis.Lag, c3, x, y, z))
    same(m.lagvander(x, 3), PolyFunctional.vander(PolyBasis.Lag, x, 3))
    same(m.lagvander2d(x, y, Seq(1, 2)), PolyFunctional.vanderNd(PolyBasis.Lag, Seq(x, y), Seq(1, 2)))
    same(m.lagvander3d(x, y, z, Seq(1, 1, 2)), PolyFunctional.vanderNd(PolyBasis.Lag, Seq(x, y, z), Seq(1, 1, 2)))
    same(m.lagder(c), PolyFunctional.der(PolyBasis.Lag, c, 1, 1.0, 0))
    same(m.lagint(c, 2, Seq(1.0), 0.5, 2.0), PolyFunctional.integ(PolyBasis.Lag, c, 2, Seq(1.0), 0.5, 2.0, 0))
    same(m.lagadd(c, c2), PolyFunctional.add(PolyBasis.Lag, c, c2))
    same(m.lagsub(c, c2), PolyFunctional.sub(PolyBasis.Lag, c, c2))
    same(m.lagmul(c, c2), PolyFunctional.mul(PolyBasis.Lag, c, c2))
    same(m.lagmulx(c), PolyFunctional.mulx(PolyBasis.Lag, c))
    same(m.lagdiv(c, c2)._1, PolyFunctional.div(PolyBasis.Lag, c, c2)._1)
    same(m.lagpow(c2, 2), PolyFunctional.pow(PolyBasis.Lag, c2, 2, 16))
    assertEquals(m.lagroots(c).toList, PolyFunctional.roots(PolyBasis.Lag, c).toList)
    same(m.lagcompanion(c), PolyFunctional.companion(PolyBasis.Lag, c))
    same(m.lagfromroots(c2), PolyFunctional.fromroots(PolyBasis.Lag, c2))
    same(m.lagline(1.0, 2.0), PolyFunctional.line(PolyBasis.Lag, 1.0, 2.0))
    same(m.lagtrim(np.array(1.0, 0.0)), np.array(1.0).reshape(1))
    val xs = np.linspace(0.0, 1.0, 6)
    val ys = xs.map(v => v * v)
    same(m.lagfit(xs, ys, 2), PolyFunctional.fit(PolyBasis.Lag, xs, ys, 2, -1.0, null)._1)
    assertEquals(m.lagfit(xs, ys, 2, full = true)._2.rank, 3)
    same(m.lagfit(xs, ys, 2, w = np.ones(6)), PolyFunctional.fit(PolyBasis.Lag, xs, ys, 2, -1.0, np.ones(6))._1)
    same(m.lag2poly(c), PolyFunctional.toPower(PolyBasis.Lag, c))
    same(m.poly2lag(c), PolyFunctional.fromPower(PolyBasis.Lag, c))
    same(m.laggauss(3)._1, PolyFunctional.gauss(PolyBasis.Lag, 3)._1)
    same(m.lagweight(x), PolyFunctional.weight(PolyBasis.Lag, x))
    assertEquals(m.Laguerre(Seq(1.0)).degree, 0)
  }
