// GENERATED by project/gen/gen_typeclasses.py -- do not edit by hand.
package numscala

/** Result type of combining two dtypes (`np.result_type`). */
trait Promote[A, B]:
  type Out
  def dtype: DType[Out]

object Promote:
  type Aux[A, B, O] = Promote[A, B] { type Out = O }
  private def make[A, B, O](d: DType[O]): Aux[A, B, O] = new Promote[A, B]:
    type Out = O
    val dtype: DType[O] = d
  given same[T](using d: DType[T]): Aux[T, T, T] = make(d)
  given p_Boolean_Byte: Aux[Boolean, Byte, Byte] = make(DType.Int8)
  given p_Boolean_Short: Aux[Boolean, Short, Short] = make(DType.Int16)
  given p_Boolean_Int: Aux[Boolean, Int, Int] = make(DType.Int32)
  given p_Boolean_Long: Aux[Boolean, Long, Long] = make(DType.Int64)
  given p_Boolean_Float: Aux[Boolean, Float, Float] = make(DType.Float32)
  given p_Boolean_Double: Aux[Boolean, Double, Double] = make(DType.Float64)
  given p_Boolean_Complex: Aux[Boolean, Complex, Complex] = make(DType.Complex128)
  given p_Byte_Boolean: Aux[Byte, Boolean, Byte] = make(DType.Int8)
  given p_Byte_Short: Aux[Byte, Short, Short] = make(DType.Int16)
  given p_Byte_Int: Aux[Byte, Int, Int] = make(DType.Int32)
  given p_Byte_Long: Aux[Byte, Long, Long] = make(DType.Int64)
  given p_Byte_Float: Aux[Byte, Float, Float] = make(DType.Float32)
  given p_Byte_Double: Aux[Byte, Double, Double] = make(DType.Float64)
  given p_Byte_Complex: Aux[Byte, Complex, Complex] = make(DType.Complex128)
  given p_Short_Boolean: Aux[Short, Boolean, Short] = make(DType.Int16)
  given p_Short_Byte: Aux[Short, Byte, Short] = make(DType.Int16)
  given p_Short_Int: Aux[Short, Int, Int] = make(DType.Int32)
  given p_Short_Long: Aux[Short, Long, Long] = make(DType.Int64)
  given p_Short_Float: Aux[Short, Float, Float] = make(DType.Float32)
  given p_Short_Double: Aux[Short, Double, Double] = make(DType.Float64)
  given p_Short_Complex: Aux[Short, Complex, Complex] = make(DType.Complex128)
  given p_Int_Boolean: Aux[Int, Boolean, Int] = make(DType.Int32)
  given p_Int_Byte: Aux[Int, Byte, Int] = make(DType.Int32)
  given p_Int_Short: Aux[Int, Short, Int] = make(DType.Int32)
  given p_Int_Long: Aux[Int, Long, Long] = make(DType.Int64)
  given p_Int_Float: Aux[Int, Float, Double] = make(DType.Float64)
  given p_Int_Double: Aux[Int, Double, Double] = make(DType.Float64)
  given p_Int_Complex: Aux[Int, Complex, Complex] = make(DType.Complex128)
  given p_Long_Boolean: Aux[Long, Boolean, Long] = make(DType.Int64)
  given p_Long_Byte: Aux[Long, Byte, Long] = make(DType.Int64)
  given p_Long_Short: Aux[Long, Short, Long] = make(DType.Int64)
  given p_Long_Int: Aux[Long, Int, Long] = make(DType.Int64)
  given p_Long_Float: Aux[Long, Float, Double] = make(DType.Float64)
  given p_Long_Double: Aux[Long, Double, Double] = make(DType.Float64)
  given p_Long_Complex: Aux[Long, Complex, Complex] = make(DType.Complex128)
  given p_Float_Boolean: Aux[Float, Boolean, Float] = make(DType.Float32)
  given p_Float_Byte: Aux[Float, Byte, Float] = make(DType.Float32)
  given p_Float_Short: Aux[Float, Short, Float] = make(DType.Float32)
  given p_Float_Int: Aux[Float, Int, Double] = make(DType.Float64)
  given p_Float_Long: Aux[Float, Long, Double] = make(DType.Float64)
  given p_Float_Double: Aux[Float, Double, Double] = make(DType.Float64)
  given p_Float_Complex: Aux[Float, Complex, Complex] = make(DType.Complex128)
  given p_Double_Boolean: Aux[Double, Boolean, Double] = make(DType.Float64)
  given p_Double_Byte: Aux[Double, Byte, Double] = make(DType.Float64)
  given p_Double_Short: Aux[Double, Short, Double] = make(DType.Float64)
  given p_Double_Int: Aux[Double, Int, Double] = make(DType.Float64)
  given p_Double_Long: Aux[Double, Long, Double] = make(DType.Float64)
  given p_Double_Float: Aux[Double, Float, Double] = make(DType.Float64)
  given p_Double_Complex: Aux[Double, Complex, Complex] = make(DType.Complex128)
  given p_Complex_Boolean: Aux[Complex, Boolean, Complex] = make(DType.Complex128)
  given p_Complex_Byte: Aux[Complex, Byte, Complex] = make(DType.Complex128)
  given p_Complex_Short: Aux[Complex, Short, Complex] = make(DType.Complex128)
  given p_Complex_Int: Aux[Complex, Int, Complex] = make(DType.Complex128)
  given p_Complex_Long: Aux[Complex, Long, Complex] = make(DType.Complex128)
  given p_Complex_Float: Aux[Complex, Float, Complex] = make(DType.Complex128)
  given p_Complex_Double: Aux[Complex, Double, Complex] = make(DType.Complex128)

/** Result type of arithmetic (`+ - * **`) between two numeric dtypes. */
trait NumPromote[A, B]:
  type Out
  def dtype: NumDType[Out]

object NumPromote:
  type Aux[A, B, O] = NumPromote[A, B] { type Out = O }
  private def make[A, B, O](d: NumDType[O]): Aux[A, B, O] = new NumPromote[A, B]:
    type Out = O
    val dtype: NumDType[O] = d
  given same[T](using d: NumDType[T]): Aux[T, T, T] = make(d)
  given n_Boolean_Byte: Aux[Boolean, Byte, Byte] = make(DType.Int8)
  given n_Boolean_Short: Aux[Boolean, Short, Short] = make(DType.Int16)
  given n_Boolean_Int: Aux[Boolean, Int, Int] = make(DType.Int32)
  given n_Boolean_Long: Aux[Boolean, Long, Long] = make(DType.Int64)
  given n_Boolean_Float: Aux[Boolean, Float, Float] = make(DType.Float32)
  given n_Boolean_Double: Aux[Boolean, Double, Double] = make(DType.Float64)
  given n_Boolean_Complex: Aux[Boolean, Complex, Complex] = make(DType.Complex128)
  given n_Byte_Boolean: Aux[Byte, Boolean, Byte] = make(DType.Int8)
  given n_Byte_Short: Aux[Byte, Short, Short] = make(DType.Int16)
  given n_Byte_Int: Aux[Byte, Int, Int] = make(DType.Int32)
  given n_Byte_Long: Aux[Byte, Long, Long] = make(DType.Int64)
  given n_Byte_Float: Aux[Byte, Float, Float] = make(DType.Float32)
  given n_Byte_Double: Aux[Byte, Double, Double] = make(DType.Float64)
  given n_Byte_Complex: Aux[Byte, Complex, Complex] = make(DType.Complex128)
  given n_Short_Boolean: Aux[Short, Boolean, Short] = make(DType.Int16)
  given n_Short_Byte: Aux[Short, Byte, Short] = make(DType.Int16)
  given n_Short_Int: Aux[Short, Int, Int] = make(DType.Int32)
  given n_Short_Long: Aux[Short, Long, Long] = make(DType.Int64)
  given n_Short_Float: Aux[Short, Float, Float] = make(DType.Float32)
  given n_Short_Double: Aux[Short, Double, Double] = make(DType.Float64)
  given n_Short_Complex: Aux[Short, Complex, Complex] = make(DType.Complex128)
  given n_Int_Boolean: Aux[Int, Boolean, Int] = make(DType.Int32)
  given n_Int_Byte: Aux[Int, Byte, Int] = make(DType.Int32)
  given n_Int_Short: Aux[Int, Short, Int] = make(DType.Int32)
  given n_Int_Long: Aux[Int, Long, Long] = make(DType.Int64)
  given n_Int_Float: Aux[Int, Float, Double] = make(DType.Float64)
  given n_Int_Double: Aux[Int, Double, Double] = make(DType.Float64)
  given n_Int_Complex: Aux[Int, Complex, Complex] = make(DType.Complex128)
  given n_Long_Boolean: Aux[Long, Boolean, Long] = make(DType.Int64)
  given n_Long_Byte: Aux[Long, Byte, Long] = make(DType.Int64)
  given n_Long_Short: Aux[Long, Short, Long] = make(DType.Int64)
  given n_Long_Int: Aux[Long, Int, Long] = make(DType.Int64)
  given n_Long_Float: Aux[Long, Float, Double] = make(DType.Float64)
  given n_Long_Double: Aux[Long, Double, Double] = make(DType.Float64)
  given n_Long_Complex: Aux[Long, Complex, Complex] = make(DType.Complex128)
  given n_Float_Boolean: Aux[Float, Boolean, Float] = make(DType.Float32)
  given n_Float_Byte: Aux[Float, Byte, Float] = make(DType.Float32)
  given n_Float_Short: Aux[Float, Short, Float] = make(DType.Float32)
  given n_Float_Int: Aux[Float, Int, Double] = make(DType.Float64)
  given n_Float_Long: Aux[Float, Long, Double] = make(DType.Float64)
  given n_Float_Double: Aux[Float, Double, Double] = make(DType.Float64)
  given n_Float_Complex: Aux[Float, Complex, Complex] = make(DType.Complex128)
  given n_Double_Boolean: Aux[Double, Boolean, Double] = make(DType.Float64)
  given n_Double_Byte: Aux[Double, Byte, Double] = make(DType.Float64)
  given n_Double_Short: Aux[Double, Short, Double] = make(DType.Float64)
  given n_Double_Int: Aux[Double, Int, Double] = make(DType.Float64)
  given n_Double_Long: Aux[Double, Long, Double] = make(DType.Float64)
  given n_Double_Float: Aux[Double, Float, Double] = make(DType.Float64)
  given n_Double_Complex: Aux[Double, Complex, Complex] = make(DType.Complex128)
  given n_Complex_Boolean: Aux[Complex, Boolean, Complex] = make(DType.Complex128)
  given n_Complex_Byte: Aux[Complex, Byte, Complex] = make(DType.Complex128)
  given n_Complex_Short: Aux[Complex, Short, Complex] = make(DType.Complex128)
  given n_Complex_Int: Aux[Complex, Int, Complex] = make(DType.Complex128)
  given n_Complex_Long: Aux[Complex, Long, Complex] = make(DType.Complex128)
  given n_Complex_Float: Aux[Complex, Float, Complex] = make(DType.Complex128)
  given n_Complex_Double: Aux[Complex, Double, Complex] = make(DType.Complex128)

/** Result type of true division (`/`) between two numeric dtypes: always inexact. */
trait DivPromote[A, B]:
  type Out
  def dtype: InexactDType[Out]

object DivPromote:
  type Aux[A, B, O] = DivPromote[A, B] { type Out = O }
  private def make[A, B, O](d: InexactDType[O]): Aux[A, B, O] = new DivPromote[A, B]:
    type Out = O
    val dtype: InexactDType[O] = d
  given d_Boolean_Boolean: Aux[Boolean, Boolean, Double] = make(DType.Float64)
  given d_Boolean_Byte: Aux[Boolean, Byte, Double] = make(DType.Float64)
  given d_Boolean_Short: Aux[Boolean, Short, Double] = make(DType.Float64)
  given d_Boolean_Int: Aux[Boolean, Int, Double] = make(DType.Float64)
  given d_Boolean_Long: Aux[Boolean, Long, Double] = make(DType.Float64)
  given d_Boolean_Float: Aux[Boolean, Float, Float] = make(DType.Float32)
  given d_Boolean_Double: Aux[Boolean, Double, Double] = make(DType.Float64)
  given d_Boolean_Complex: Aux[Boolean, Complex, Complex] = make(DType.Complex128)
  given d_Byte_Boolean: Aux[Byte, Boolean, Double] = make(DType.Float64)
  given d_Byte_Byte: Aux[Byte, Byte, Double] = make(DType.Float64)
  given d_Byte_Short: Aux[Byte, Short, Double] = make(DType.Float64)
  given d_Byte_Int: Aux[Byte, Int, Double] = make(DType.Float64)
  given d_Byte_Long: Aux[Byte, Long, Double] = make(DType.Float64)
  given d_Byte_Float: Aux[Byte, Float, Float] = make(DType.Float32)
  given d_Byte_Double: Aux[Byte, Double, Double] = make(DType.Float64)
  given d_Byte_Complex: Aux[Byte, Complex, Complex] = make(DType.Complex128)
  given d_Short_Boolean: Aux[Short, Boolean, Double] = make(DType.Float64)
  given d_Short_Byte: Aux[Short, Byte, Double] = make(DType.Float64)
  given d_Short_Short: Aux[Short, Short, Double] = make(DType.Float64)
  given d_Short_Int: Aux[Short, Int, Double] = make(DType.Float64)
  given d_Short_Long: Aux[Short, Long, Double] = make(DType.Float64)
  given d_Short_Float: Aux[Short, Float, Float] = make(DType.Float32)
  given d_Short_Double: Aux[Short, Double, Double] = make(DType.Float64)
  given d_Short_Complex: Aux[Short, Complex, Complex] = make(DType.Complex128)
  given d_Int_Boolean: Aux[Int, Boolean, Double] = make(DType.Float64)
  given d_Int_Byte: Aux[Int, Byte, Double] = make(DType.Float64)
  given d_Int_Short: Aux[Int, Short, Double] = make(DType.Float64)
  given d_Int_Int: Aux[Int, Int, Double] = make(DType.Float64)
  given d_Int_Long: Aux[Int, Long, Double] = make(DType.Float64)
  given d_Int_Float: Aux[Int, Float, Double] = make(DType.Float64)
  given d_Int_Double: Aux[Int, Double, Double] = make(DType.Float64)
  given d_Int_Complex: Aux[Int, Complex, Complex] = make(DType.Complex128)
  given d_Long_Boolean: Aux[Long, Boolean, Double] = make(DType.Float64)
  given d_Long_Byte: Aux[Long, Byte, Double] = make(DType.Float64)
  given d_Long_Short: Aux[Long, Short, Double] = make(DType.Float64)
  given d_Long_Int: Aux[Long, Int, Double] = make(DType.Float64)
  given d_Long_Long: Aux[Long, Long, Double] = make(DType.Float64)
  given d_Long_Float: Aux[Long, Float, Double] = make(DType.Float64)
  given d_Long_Double: Aux[Long, Double, Double] = make(DType.Float64)
  given d_Long_Complex: Aux[Long, Complex, Complex] = make(DType.Complex128)
  given d_Float_Boolean: Aux[Float, Boolean, Float] = make(DType.Float32)
  given d_Float_Byte: Aux[Float, Byte, Float] = make(DType.Float32)
  given d_Float_Short: Aux[Float, Short, Float] = make(DType.Float32)
  given d_Float_Int: Aux[Float, Int, Double] = make(DType.Float64)
  given d_Float_Long: Aux[Float, Long, Double] = make(DType.Float64)
  given d_Float_Float: Aux[Float, Float, Float] = make(DType.Float32)
  given d_Float_Double: Aux[Float, Double, Double] = make(DType.Float64)
  given d_Float_Complex: Aux[Float, Complex, Complex] = make(DType.Complex128)
  given d_Double_Boolean: Aux[Double, Boolean, Double] = make(DType.Float64)
  given d_Double_Byte: Aux[Double, Byte, Double] = make(DType.Float64)
  given d_Double_Short: Aux[Double, Short, Double] = make(DType.Float64)
  given d_Double_Int: Aux[Double, Int, Double] = make(DType.Float64)
  given d_Double_Long: Aux[Double, Long, Double] = make(DType.Float64)
  given d_Double_Float: Aux[Double, Float, Double] = make(DType.Float64)
  given d_Double_Double: Aux[Double, Double, Double] = make(DType.Float64)
  given d_Double_Complex: Aux[Double, Complex, Complex] = make(DType.Complex128)
  given d_Complex_Boolean: Aux[Complex, Boolean, Complex] = make(DType.Complex128)
  given d_Complex_Byte: Aux[Complex, Byte, Complex] = make(DType.Complex128)
  given d_Complex_Short: Aux[Complex, Short, Complex] = make(DType.Complex128)
  given d_Complex_Int: Aux[Complex, Int, Complex] = make(DType.Complex128)
  given d_Complex_Long: Aux[Complex, Long, Complex] = make(DType.Complex128)
  given d_Complex_Float: Aux[Complex, Float, Complex] = make(DType.Complex128)
  given d_Complex_Double: Aux[Complex, Double, Complex] = make(DType.Complex128)
  given d_Complex_Complex: Aux[Complex, Complex, Complex] = make(DType.Complex128)

/** Inexact dtype used for results of transcendental functions (`np.sqrt` of int is float64). */
trait ToInexact[T]:
  type Out
  def dtype: InexactDType[Out]

object ToInexact:
  type Aux[T, O] = ToInexact[T] { type Out = O }
  private def make[T, O](d: InexactDType[O]): Aux[T, O] = new ToInexact[T]:
    type Out = O
    val dtype: InexactDType[O] = d
  given u_Boolean: Aux[Boolean, Double] = make(DType.Float64)
  given u_Byte: Aux[Byte, Double] = make(DType.Float64)
  given u_Short: Aux[Short, Double] = make(DType.Float64)
  given u_Int: Aux[Int, Double] = make(DType.Float64)
  given u_Long: Aux[Long, Double] = make(DType.Float64)
  given u_Float: Aux[Float, Float] = make(DType.Float32)
  given u_Double: Aux[Double, Double] = make(DType.Float64)
  given u_Complex: Aux[Complex, Complex] = make(DType.Complex128)

/** Real floating dtype used for results of real-only float functions (`np.floor`, `np.arctan2`). */
trait ToFloat[T]:
  type Out
  def dtype: FloatDType[Out]

object ToFloat:
  type Aux[T, O] = ToFloat[T] { type Out = O }
  private def make[T, O](d: FloatDType[O]): Aux[T, O] = new ToFloat[T]:
    type Out = O
    val dtype: FloatDType[O] = d
  given u_Boolean: Aux[Boolean, Double] = make(DType.Float64)
  given u_Byte: Aux[Byte, Double] = make(DType.Float64)
  given u_Short: Aux[Short, Double] = make(DType.Float64)
  given u_Int: Aux[Int, Double] = make(DType.Float64)
  given u_Long: Aux[Long, Double] = make(DType.Float64)
  given u_Float: Aux[Float, Float] = make(DType.Float32)
  given u_Double: Aux[Double, Double] = make(DType.Float64)

/** Accumulator dtype of `sum`/`prod`/`cumsum` (small integers widen to int64 like NumPy). */
trait SumOf[T]:
  type Out
  def dtype: NumDType[Out]

object SumOf:
  type Aux[T, O] = SumOf[T] { type Out = O }
  private def make[T, O](d: NumDType[O]): Aux[T, O] = new SumOf[T]:
    type Out = O
    val dtype: NumDType[O] = d
  given u_Boolean: Aux[Boolean, Long] = make(DType.Int64)
  given u_Byte: Aux[Byte, Long] = make(DType.Int64)
  given u_Short: Aux[Short, Long] = make(DType.Int64)
  given u_Int: Aux[Int, Long] = make(DType.Int64)
  given u_Long: Aux[Long, Long] = make(DType.Int64)
  given u_Float: Aux[Float, Float] = make(DType.Float32)
  given u_Double: Aux[Double, Double] = make(DType.Float64)
  given u_Complex: Aux[Complex, Complex] = make(DType.Complex128)

/** Real dtype of `var`/`std`/`abs` results for inexact inputs (complex -> float64). */
trait RealOf[T]:
  type Out
  def dtype: FloatDType[Out]

object RealOf:
  type Aux[T, O] = RealOf[T] { type Out = O }
  private def make[T, O](d: FloatDType[O]): Aux[T, O] = new RealOf[T]:
    type Out = O
    val dtype: FloatDType[O] = d
  given u_Boolean: Aux[Boolean, Double] = make(DType.Float64)
  given u_Byte: Aux[Byte, Double] = make(DType.Float64)
  given u_Short: Aux[Short, Double] = make(DType.Float64)
  given u_Int: Aux[Int, Double] = make(DType.Float64)
  given u_Long: Aux[Long, Double] = make(DType.Float64)
  given u_Float: Aux[Float, Float] = make(DType.Float32)
  given u_Double: Aux[Double, Double] = make(DType.Float64)
  given u_Complex: Aux[Complex, Double] = make(DType.Float64)

/** Result dtype of `np.abs` (complex -> float64). */
trait AbsOf[T]:
  type Out
  def dtype: DType[Out]

object AbsOf:
  type Aux[T, O] = AbsOf[T] { type Out = O }
  private def make[T, O](d: DType[O]): Aux[T, O] = new AbsOf[T]:
    type Out = O
    val dtype: DType[O] = d
  given u_Boolean: Aux[Boolean, Boolean] = make(DType.Bool)
  given u_Byte: Aux[Byte, Byte] = make(DType.Int8)
  given u_Short: Aux[Short, Short] = make(DType.Int16)
  given u_Int: Aux[Int, Int] = make(DType.Int32)
  given u_Long: Aux[Long, Long] = make(DType.Int64)
  given u_Float: Aux[Float, Float] = make(DType.Float32)
  given u_Double: Aux[Double, Double] = make(DType.Float64)
  given u_Complex: Aux[Complex, Double] = make(DType.Float64)

/** Bitwise / logical operations, available for `bool` and integer dtypes. */
trait BitOps[T]:
  def and(x: T, y: T): T
  def or(x: T, y: T): T
  def xor(x: T, y: T): T
  def not(x: T): T

object BitOps:
  given BitOps[Boolean] with
    def and(x: Boolean, y: Boolean): Boolean = x && y
    def or(x: Boolean, y: Boolean): Boolean = x || y
    def xor(x: Boolean, y: Boolean): Boolean = x ^ y
    def not(x: Boolean): Boolean = !x
  given fromInt[T](using d: IntDType[T]): BitOps[T] with
    def and(x: T, y: T): T = d.and(x, y)
    def or(x: T, y: T): T = d.or(x, y)
    def xor(x: T, y: T): T = d.xor(x, y)
    def not(x: T): T = d.invert(x)

/** Supplies a dtype for a type parameter, defaulting to `float64` when it is not
  * otherwise determined — so `np.zeros(3)` is a float array while
  * `np.zeros[Int](3)` is an int32 array.
  */
trait DefaultDType[T]:
  def dtype: DType[T]

object DefaultDType extends LowPriorityDefaultDType:
  given float64Default: DefaultDType[Double] with
    def dtype: DType[Double] = DType.Float64

trait LowPriorityDefaultDType:
  given fromDType[T](using d: DType[T]): DefaultDType[T] with
    def dtype: DType[T] = d
